### ISSUE TITLE
[HxModal] and [HxOffcanvas] disable main scrolling on remove/close

### ISSUE THREAD

**Issue by stayboy** [havit/Havit.Blazor#110]
For scrolling pages, HxModal and HxOffCanvax on pop, set body style to overflow = hidden. And does not remove style on either component HideAsync action

**Comment by hakenr** [comment]
@crdo Can you take a look at this, please?

**Comment by crdo** [comment]
@stayboy I am not able to reproduce the described behaviour. The [documentation page](https://havit.blazor.eu/components/HxOffcanvas) is scrollable and the overflow: hidden; on the body element is removed as soon as the dialog is closed.
May I please ask you to provide some minimal repository reproducing your issue?

**Comment by stayboy** [comment]
> @stayboy I am not able to reproduce the described behaviour. The [documentation page](https://havit.blazor.eu/components/HxOffcanvas) is scrollable and the overflow: hidden; on the body element is removed as soon as the dialog is closed. May I please ask you to provide some minimal repository reproducing your issue?

Try the backdrop sample here
![image](https://user-images.githubusercontent.com/10756019/162403302-7468f7ca-87c3-4c55-89f2-7fd57a388cb2.png)

**Comment by crdo** [comment]
Tried, working as expected...

**Comment by stayboy** [comment]
> Tried, working as expected...

I saw the problem. When you hit to show the Canvax, rather than close, hit any the source Tab from the picture I sent, and the scrolls will are off forever. My guess is, when HxOffCanvax is not closed and State changes someway or the other that forces HxOffCanvax to hide by itself, You are locked out of ever seeing your scroll bar. Just try it.

![image](https://user-images.githubusercontent.com/10756019/162426854-b9bf0b4f-e24d-4be7-9ec0-0c187aa37932.png)

**Comment by crdo** [comment]
OK, I get it. 

1. Open the Offcanvas w/o backdrop
2. Click the Source tab
3. The content of the Demo tab is removed from the DOM and the css inlined to the body element is not cleaned up

I guess this is not a real world scenario, but we can have a look into it. Cc @hakenr

**Comment by crdo** [comment]
You simply cannot remove the whole Offcanvas/Modal component from the DOM while it is open and scrolling is disabled. If you do it, overflow: hidden remains set on the body and you cannot scroll.

This is a wrong application design rather than issue of Havit.Blazor. If you do the same with Bootstrap only, you will get exactly the same result.

If you still believe that it is somehow related to changing state or calling StateHasChanged, please submit a repository reproducing your issue.

**Comment by hakenr** [comment]
We are calling `offcanvas.dispose()` and we believe the dispose should do the cleanup. Will try to create a simple repro for Bootstrap and report to them. (@Harvey1214)

**Comment by Harvey1214** [comment]
> This should be addressed in v5.2.0-beta1. Stable release is coming soon.

Refer to https://github.com/twbs/bootstrap/issues/36397

**Comment by hakenr** [comment]
It seems that sometimes our `dispose()` function gets called while the offcanvas/modal hiding transition is still running.
The transition-complete callback which clean-ups the `body` fails in such case.

This can be reproduced in our `HxListLayout` component when I change nesting and make the `HxOffcanvas` to be inside of `HxFilterForm` instead of having the `HxFilterForm` inside the `HxOffcanvas.Body`.
Then, when you click _Apply_ button in the `HxListLayout` filter-offcanvas footer, this error occurs:
```
offcanvas.js:146  Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at offcanvas.js:146:21
    at g (index.js:226:51)
    at HTMLDivElement.a (index.js:247:5)
    at s (index.js:71:11)
    at index.js:253:7
```
Where it is line 146 in hide() where the callback does not find the `classList` any more (as the `dispose()` already took place):
![image](https://github.com/havit/Havit.Blazor/assets/12828888/811043e6-c55b-41a0-9ac1-e96129b586c2)


I will try to add some defensive logic to `HxOffcanvas` and `HxModal` to postpone our `dispose()` to `onHidden` event handler if it gets called while hiding is still in progress.

**Comment by hakenr** [comment]
Issue persists in Bootstrap; reverting to waiting status.

Bootstrap's `dispose()` method fails to reset scrollbars, leaving `overflow: hidden` on the `body` element intact. Neither `Offcanvas.js:dispose()` nor `Modal.js:dispose()` invoke `ScrollBarHelper().reset()`. Currently, this reset is only triggered in the `hide()` logic of Bootstrap's Offcanvas/Modal. However, this approach is ineffective for us because Blazor removes elements from the DOM, causing the `hide()` call to fail before `reset()` can be executed.
