### ISSUE TITLE
[HxGrid] DataProvider called with SortItems null (where it shouldn't)

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#344]
Tried the v3.0.0-pre1 in 003.GOR-G3 and realized that the grids (DataProvider methods) fail with this (or similar) exception:
```
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[SortingItem`1,SortItem](IEnumerable`1 source, Func`2 selector)
   at Havit.GoranG3.Web.Client.Pages.Crm.ContactDetail.GetBussinesCases(GridDataProviderRequest`1 request) in D:\Development\003.GOR-G3\Web.Client\Pages\Crm\ContactDetail.razor.cs:line 109
   at Havit.GoranG3.Web.Client.Pages.Crm.BusinessCases.BusinessCaseListGrid.LoadBusinessCases(GridDataProviderRequest`1 request) in D:\Development\003.GOR-G3\Web.Client\Pages\Crm\BusinessCases\BusinessCaseListGrid.razor.cs:line 59
   at Havit.Blazor.Components.Web.Bootstrap.HxGrid`1.<InvokeDataProviderInternal>d__193[[Havit.GoranG3.Contracts.Crm.BusinessCaseListItem, Havit.GoranG3.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Havit.Blazor.Components.Web.Bootstrap.HxGrid`1.<RefreshPaginationDataCoreAsync>d__191[[Havit.GoranG3.Contracts.Crm.BusinessCaseListItem, Havit.GoranG3.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Havit.Blazor.Components.Web.Bootstrap.HxGrid`1.<RefreshDataAsync>d__190[[Havit.GoranG3.Contracts.Crm.BusinessCaseListItem, Havit.GoranG3.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Havit.GoranG3.Web.Client.Pages.Crm.ContactDetail.OnParametersSetAsync() in D:\Development\003.GOR-G3\Web.Client\Pages\Crm\ContactDetail.razor.cs:line 48
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

The request.SortItems is null where it is not expected (the HxGrid is configured with default sorting).

cc @jirikanda, @crdo (no-go for v3.0.0 release)
...I will try to investigate further tomorrow

**Comment by hakenr** [comment]
resolved within #345 (seems to be same cause)
