### ISSUE TITLE
[HxPopover] Cannot read properties of null (reading 'removeEventListener') when leaving page early

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#38]
When leaving the page before the popover gets fully initialized:
```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot read properties of null (reading 'removeEventListener')
      TypeError: Cannot read properties of null (reading 'removeEventListener')
          at destroy (https://localhost:44381/_content/Havit.Blazor.Components.Web.Bootstrap/HxPopover.js:29:10)
          at Module.createOrUpdate (https://localhost:44381/_content/Havit.Blazor.Components.Web.Bootstrap/HxPopover.js:3:2)
          at https://localhost:44381/_framework/blazor.webassembly.js:1:3942
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:44381/_framework/blazor.webassembly.js:1:3908)
          at Object.w [as invokeJSFromDotNet] (https://localhost:44381/_framework/blazor.webassembly.js:1:64232)
          at _mono_wasm_invoke_js_blazor (https://localhost:44381/_framework/dotnet.5.0.12.js:1:190800)
          at do_icall (wasm://wasm/00aba242:wasm-function[10596]:0x194e4e)
          at do_icall_wrapper (wasm://wasm/00aba242:wasm-function[3305]:0x79df9)
          at interp_exec_method (wasm://wasm/00aba242:wasm-function[2155]:0x44ad3)
Microsoft.JSInterop.JSException: Cannot read properties of null (reading 'removeEventListener')
TypeError: Cannot read properties of null (reading 'removeEventListener')
    at destroy (https://localhost:44381/_content/Havit.Blazor.Components.Web.Bootstrap/HxPopover.js:29:10)
    at Module.createOrUpdate (https://localhost:44381/_content/Havit.Blazor.Components.Web.Bootstrap/HxPopover.js:3:2)
    at https://localhost:44381/_framework/blazor.webassembly.js:1:3942
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:44381/_framework/blazor.webassembly.js:1:3908)
    at Object.w [as invokeJSFromDotNet] (https://localhost:44381/_framework/blazor.webassembly.js:1:64232)
    at _mono_wasm_invoke_js_blazor (https://localhost:44381/_framework/dotnet.5.0.12.js:1:190800)
    at do_icall (wasm://wasm/00aba242:wasm-function[10596]:0x194e4e)
    at do_icall_wrapper (wasm://wasm/00aba242:wasm-function[3305]:0x79df9)
    at interp_exec_method (wasm://wasm/00aba242:wasm-function[2155]:0x44ad3)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__15`1[[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at Havit.Blazor.Components.Web.Bootstrap.Internal.HxTooltipInternalBase.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

**We need to make the JS test for popover instance existence.**

**Comment by hakenr** [comment]
WIP @Harvey1214
