### ISSUE TITLE
[HxTooltip] JS error when navigating to another "page" (while disposing?)

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#457]
Waiting for details from TULIP.

**Comment by hakenr** [comment]
Dobrý deň,
posielam popis spomínanej chyby s Bootstrap Tooltip pri presmerovaní na page v komponente SupportRequestGrid.razor.cs. 

Scenár: Po kliku na edit button v riadku gridu (Telerik grid) ukladám vybranú entitu do session a následne pomocou NavigationManager presmerujem na page detail entity.
![image](https://user-images.githubusercontent.com/12828888/216102965-efd4131b-1878-41d0-b651-521a3c7a9f84.png)

Problém: Ak nastavím metóde NavigationManager.NavigateTo  parameter forseLoad=false, po presmerovaní consola vypíše error “Cannot read properties of null (reading ‘template’)”., aj v prípade ak  je page „detail“ prázdna.
![image](https://user-images.githubusercontent.com/12828888/216103041-22ea501a-d474-402d-9afc-d847d86f7b70.png)

Používame Nuget Havit.Blazor.Components.Web.Bootstrap v. 3.2.6.

Ďakujem za pomoc,
S pozdravom / Best regards,

Daniel Juračka

**Comment by hakenr** [comment]
Probably same error - navigating from the page when tooltip is visible:
https://stackoverflow.com/questions/69766375/typeerror-cannot-read-properties-of-null-reading-template-on-bootstrap-tool

**Comment by hakenr** [comment]
Note: The "_activeTrigger" issues still reproduces in `release/v4` branch (currently Bootstrap 5.3.0-alpha1).

**Comment by hakenr** [comment]
Something to explore: https://github.com/twbs/bootstrap/pull/38018

**Comment by sebastianbk** [comment]
I still have this issue. Here's a stack trace:

```
[2023-11-28T14:29:23.368Z] Error: Microsoft.JSInterop.JSException: bootstrap is not defined
ReferenceError: bootstrap is not defined
    at Module.initialize (https://app.heyhack.com/_content/Havit.Blazor.Components.Web.Bootstrap/HxTooltip.js?v=2.0.0%2Ba8df7d1f865fa0872d8fdb75e7d97838d252495f:9:2)
    at https://app.heyhack.com/_framework/blazor.server.js:1:3244
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://app.heyhack.com/_framework/blazor.server.js:1:3201)
    at Yt._invokeClientMethod (https://app.heyhack.com/_framework/blazor.server.js:1:60713)
    at Yt._processIncomingData (https://app.heyhack.com/_framework/blazor.server.js:1:58188)
    at Yt.connection.onreceive (https://app.heyhack.com/_framework/blazor.server.js:1:51829)
    at s.onmessage (https://app.heyhack.com/_framework/blazor.server.js:1:79974)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at Havit.Blazor.Components.Web.Bootstrap.Internal.HxTooltipInternalBase.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by hakenr** [comment]
@sebastianbk, I think you are addressing a different symptom, and you have correctly filed a separate issue #677.
