### ISSUE TITLE
TaskCanceledException - Error when switching pages with the new .Net8 application template

### ISSUE THREAD

**Issue by leonardopugliese** [havit/Havit.Blazor#674]
Using the HxSearchBox component with the new Blazor .NET8 application template everything works perfectly until I change the page and I get the error message
`Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at Havit.Blazor.Components.Web.Bootstrap.HxDropdownToggleElement.DisposeAsyncCore()
   at Havit.Blazor.Components.Web.Bootstrap.HxDropdownToggleElement.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<ProcessDisposalQueueInExistingBatch>g__GetHandledAsynchronousDisposalErrorsTask|79_0(Task result)
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit '5XDbktXsweYHfhVjsiHktbkjxdJfnLegCfcSz43gAgw'.
`
I used the code from HxSearchBoxTest.razor as the test base

**Comment by hakenr** [comment]
With every single release of .NET, it seems there are new exceptions types used in disposing workflow... :-)
I will take a look at it, it seems to be an obvious fix.

**Comment by leonardopugliese** [comment]
HI! I updated to version 4.3.3 which should contain the fix but I still get an error message :
`
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: Cannot read properties of null (reading 'removeEventListener')
TypeError: Cannot read properties of null (reading 'removeEventListener')
    at Module.dispose (https://localhost:7295/_content/Havit.Blazor.Components.Web.Bootstrap/HxSearchBox.js?v=2.0.0%2Ba8df7d1f865fa0872d8fdb75e7d97838d252495f:46:18)
    at https://localhost:7295/_framework/blazor.web.js:1:3244
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://localhost:7295/_framework/blazor.web.js:1:3201)
    at fn._invokeClientMethod (https://localhost:7295/_framework/blazor.web.js:1:62541)
    at fn._processIncomingData (https://localhost:7295/_framework/blazor.web.js:1:60016)
    at connection.onreceive (https://localhost:7295/_framework/blazor.web.js:1:53657)
    at i.onmessage (https://localhost:7295/_framework/blazor.web.js:1:81802)

Microsoft.JSInterop.JSException: Cannot read properties of null (reading 'removeEventListener')
TypeError: Cannot read properties of null (reading 'removeEventListener')
    at Module.dispose (https://localhost:7295/_content/Havit.Blazor.Components.Web.Bootstrap/HxSearchBox.js?v=2.0.0%2Ba8df7d1f865fa0872d8fdb75e7d97838d252495f:46:18)
    at https://localhost:7295/_framework/blazor.web.js:1:3244
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://localhost:7295/_framework/blazor.web.js:1:3201)
    at fn._invokeClientMethod (https://localhost:7295/_framework/blazor.web.js:1:62541)
    at fn._processIncomingData (https://localhost:7295/_framework/blazor.web.js:1:60016)
    at connection.onreceive (https://localhost:7295/_framework/blazor.web.js:1:53657)
    at i.onmessage (https://localhost:7295/_framework/blazor.web.js:1:81802)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at Havit.Blazor.Components.Web.Bootstrap.HxSearchBox`1.DisposeAsyncCore()
   at Havit.Blazor.Components.Web.Bootstrap.HxSearchBox`1.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<ProcessDisposalQueueInExistingBatch>g__GetHandledAsynchronousDisposalErrorsTask|79_0(Task result)
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit '5_SVhqO-Mk5w_ALKq3PAlN7sHbGFnlQZkSy2TAF42I4'.

Microsoft.JSInterop.JSException: Cannot read properties of null (reading 'removeEventListener')
TypeError: Cannot read properties of null (reading 'removeEventListener')
    at Module.dispose (https://localhost:7295/_content/Havit.Blazor.Components.Web.Bootstrap/HxSearchBox.js?v=2.0.0%2Ba8df7d1f865fa0872d8fdb75e7d97838d252495f:46:18)
    at https://localhost:7295/_framework/blazor.web.js:1:3244
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://localhost:7295/_framework/blazor.web.js:1:3201)
    at fn._invokeClientMethod (https://localhost:7295/_framework/blazor.web.js:1:62541)
    at fn._processIncomingData (https://localhost:7295/_framework/blazor.web.js:1:60016)
    at connection.onreceive (https://localhost:7295/_framework/blazor.web.js:1:53657)
    at i.onmessage (https://localhost:7295/_framework/blazor.web.js:1:81802)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at Havit.Blazor.Components.Web.Bootstrap.HxSearchBox`1.DisposeAsyncCore()
   at Havit.Blazor.Components.Web.Bootstrap.HxSearchBox`1.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<ProcessDisposalQueueInExistingBatch>g__GetHandledAsynchronousDisposalErrorsTask|79_0(Task result)
`
I used the code from HxSearchBoxTest.razor  as a test
