### ISSUE TITLE
[HxInputTags] `FocusAsync` fails when navigating from screen (Unable to focus an invalid element.)

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#716]
1. Basic Demo
2. Open dropdown by typing any valid value.
3. While the dropdown is open, navigate to any other page (e.g. by clicking some other item in sidebar).

...JavaScript error gets logged to the console:
```
Uncaught (in promise) Error: Microsoft.JSInterop.JSException: Unable to focus an invalid element.
Error: Unable to focus an invalid element.
    at Object.focus (blazor.webassembly.js?v=rcIWTVNnYus6VWf2Z2U1g_JzlC07Ym02cFjHtI59Xsc:1:32381)
    at blazor.webassembly.js?v=rcIWTVNnYus6VWf2Z2U1g_JzlC07Ym02cFjHtI59Xsc:1:2878
    at new Promise (<anonymous>)
    at g.beginInvokeJSFromDotNet (blazor.webassembly.js?v=rcIWTVNnYus6VWf2Z2U1g_JzlC07Ym02cFjHtI59Xsc:1:2835)
    at Object.bn [as invokeJSJson] (blazor.webassembly.js?v=rcIWTVNnYus6VWf2Z2U1g_JzlC07Ym02cFjHtI59Xsc:1:58561)
    at invoke-js.ts:233:31
    at Ul (invoke-js.ts:276:5)
    at 00b1e8b6:0x1faee
    at 00b1e8b6:0x1bf8b
    at 00b1e8b6:0xf172
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext(localhost/)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(:44376/IJSRuntime jsRuntime, String identifier, Object[] args)
   at :44376/Havit.Blazor.Components.Web.Bootstrap.Internal.HxInputTagsAutosuggestInputInternal.FocusAsync() in D:\Development\002.HFW-Havit.Blazor\Havit.Blazor.Components.Web.Bootstrap\Tags\Internal\HxInputTagsAutosuggestInputInternal.razor.cs:line 39
   at :44376/Havit.Blazor.Components.Web.Bootstrap.Internal.HxInputTagsInternal.FocusAsync() in D:\Development\002.HFW-Havit.Blazor\Havit.Blazor.Components.Web.Bootstrap\Tags\Internal\HxInputTagsInternal.razor.cs:line 183
   at :44376/Havit.Blazor.Components.Web.Bootstrap.Internal.HxInputTagsInternal.AddTagWithEventCallbackAsync(String tag) in D:\Development\002.HFW-Havit.Blazor\Havit.Blazor.Components.Web.Bootstrap\Tags\Internal\HxInputTagsInternal.razor.cs:line 163
   at :44376/Havit.Blazor.Components.Web.Bootstrap.Internal.HxInputTagsInternal.TryProcessCustomTagsAsync(Boolean keepLastTagForSuggestion) in D:\Development\002.HFW-Havit.Blazor\Havit.Blazor.Components.Web.Bootstrap\Tags\Internal\HxInputTagsInternal.razor.cs:line 296
   at :44376/Havit.Blazor.Components.Web.Bootstrap.Internal.HxInputTagsInternal.HandleDropdownHidden() in D:\Development\002.HFW-Havit.Blazor\Havit.Blazor.Components.Web.Bootstrap\Tags\Internal\HxInputTagsInternal.razor.cs:line 489
    at g.endInvokeDotNetFromJS (blazor.webassembly.js?v=rcIWTVNnYus6VWf2Z2U1g_JzlC07Ym02cFjHtI59Xsc:1:3136)
    at Object.gn [as endInvokeDotNetFromJS] (blazor.webassembly.js?v=rcIWTVNnYus6VWf2Z2U1g_JzlC07Ym02cFjHtI59Xsc:1:58655)
    at invoke-js.ts:233:31
    at Ul (invoke-js.ts:276:5)
    at 00b1e8b6:0x1faee
    at 00b1e8b6:0x1bf8b
    at 00b1e8b6:0xf172
    at 00b1e8b6:0x1e7e4
    at 00b1e8b6:0x1efda
    at 00b1e8b6:0xcfec
```

**Comment by hakenr** [comment]
The inputElement is removed from DOM before the `focusAsync()` method is executed (Blazor JavaScript).
