### ISSUE TITLE
[HxFileInputBase] not working cancel

### ISSUE THREAD

**Issue by petrkasnal** [havit/Havit.Blazor#87]
Hi, i use HxInputFile and everything is good. I tried your example on https://havit.blazor.eu/components/HxInputFileCore/. I add cancel button for remove image and it doesn't work. When i click on cancel button i got this error. 

`<HxInputFile @ref="hxInputFileComponent" Accept="image/*"  />
<HxButton Text="Cancel" Color="ThemeColor.Danger" OnClick="() => hxInputFileComponent.ResetAsync()" />`

[2022-03-07T15:39:05.964Z] Error: Microsoft.JSInterop.JSException: inputElement.requests is not iterable
TypeError: inputElement.requests is not iterable
    at Module.reset (https://localhost:44327/_content/Havit.Blazor.Components.Web/HxInputFileCore.js:95:37)
    at https://localhost:44327/_framework/blazor.server.js:1:3501
    at new Promise (<anonymous>)
    at kt.beginInvokeJSFromDotNet (https://localhost:44327/_framework/blazor.server.js:1:3475)
    at https://localhost:44327/_framework/blazor.server.js:1:72001
    at Array.forEach (<anonymous>)
    at kt._invokeClientMethod (https://localhost:44327/_framework/blazor.server.js:1:71987)
    at kt._processIncomingData (https://localhost:44327/_framework/blazor.server.js:1:70029)
    at vt.connection.onreceive (https://localhost:44327/_framework/blazor.server.js:1:64432)
    at WebSocket.o.onmessage (https://localhost:44327/_framework/blazor.server.js:1:48766)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at Havit.Blazor.Components.Web.HxInputFileCore.ResetAsync() in D:\Download\Havit.Blazor-master\Havit.Blazor-master\Havit.Blazor.Components.Web\Files\HxInputFileCore.cs:line 195
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Havit.Blazor.Components.Web.Bootstrap.HxButton.HandleClickCore(MouseEventArgs mouseEventArgs) in D:\Download\Havit.Blazor-master\Havit.Blazor-master\Havit.Blazor.Components.Web.Bootstrap\Buttons\HxButton.razor.cs:line 293
   at Havit.Blazor.Components.Web.Bootstrap.HxButton.HandleClick(MouseEventArgs mouseEventArgs) in D:\Download\Havit.Blazor-master\Havit.Blazor-master\Havit.Blazor.Components.Web.Bootstrap\Buttons\HxButton.razor.cs:line 281
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by hakenr** [comment]
We did some changes in `HxInputFileCore` few days ago. This might be a regression. Will look into it and get back to you...

**Comment by petrkasnal** [comment]
@hakenr ok thank you :)

**Comment by hakenr** [comment]
Fixed in release 2.2.4

**Comment by petrkasnal** [comment]
Great! Thank you :)
