### ISSUE TITLE
[HxMultiSelect] System.InvalidOperationException: ElementReference has not been configured correctly.

### ISSUE THREAD

**Issue by kutum** [havit/Havit.Blazor#871]
I have a blazor server .net 6.0 application. I get this error when I click on a component

```
blazor.server.js:1 Uncaught (in promise) Error: System.InvalidOperationException: ElementReference has not been configured correctly.
   at Microsoft.AspNetCore.Components.ElementReferenceExtensions.GetJSRuntime(ElementReference elementReference)
   at Microsoft.AspNetCore.Components.ElementReferenceExtensions.FocusAsync(ElementReference elementReference, Boolean preventScroll)
   at Havit.Blazor.Components.Web.Bootstrap.Internal.HxMultiSelectInternal`2.HandleJsShown(ConsumerServices)
    at kt.endInvokeDotNetFromJS (blazor.server.js:1:3700)
    at blazor.server.js:1:72077
    at Array.forEach (<anonymous>)
    at kt._invokeClientMethod (blazor.server.js:1:72063)
    at kt._processIncomingData (blazor.server.js:1:70105)
    at connection.onreceive (blazor.server.js:1:64508)
    at o.onmessage (blazor.server.js:1:48842)
```

Havit.Blazor.Components.Web.Bootstrap = 4.6.12

**Comment by hakenr** [comment]
Hello @kutum,
thanks for reporting this issue. Can you please provide us with a minimal repro project so we can investigate the issue?
Thank you!

**Comment by JacobKrings** [comment]
We are also experiencing this issue. I've attached a sample solution. Error occurs when opening the multi select dropdown. Should be the colors dropdown you see when you launch the project.
[HavitMultiSelectError.zip](https://github.com/user-attachments/files/17076026/HavitMultiSelectError.zip)

**Comment by hakenr** [comment]
Hello @kutum and @JacobRustyDev,

Thanks for providing the repro. The issue actually reproduces in our own demos as well. 😇

I'll commit a fix shortly.
