### ISSUE TITLE
[HxSideBar] Localizer error?

### ISSUE THREAD

**Issue by rgbinnovation** [havit/Havit.Blazor#901]
Hi,

Just added Havit to my brand new project to test it out, and I'm mixing it with external CSS (a theme I bought):

I was playing around with the default COUNTER page, and tried putting a HxSideBar into the page. I was able to see it load, and suddenly it throws a Localizer error:

```
InvalidOperationException: Cannot provide a value for property 'Localizer' on type 'Havit.Blazor.Components.Web.Bootstrap.HxSidebar'. There is no registered service of type 'Microsoft.Extensions.Localization.IStringLocalizer`1[Havit.Blazor.Components.Web.Bootstrap.HxSpinner]'.


dotnet watch 🚀 Started
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5211
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/rgb/Repositories/XXX.IO2/XXX/XXX
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Cannot provide a value for property 'Localizer' on type 'Havit.Blazor.Components.Web.Bootstrap.HxSidebar'. There is no registered service of type 'Microsoft.Extensions.Localization.IStringLocalizer`1[Havit.Blazor.Components.Web.Bootstrap.HxSpinner]'.
      System.InvalidOperationException: Cannot provide a value for property 'Localizer' on type 'Havit.Blazor.Components.Web.Bootstrap.HxSidebar'. There is no registered service of type 'Microsoft.Extensions.Localization.IStringLocalizer`1[Havit.Blazor.Components.Web.Bootstrap.HxSpinner]'.
         at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass9_0.<CreatePropertyInjector>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
         at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'mvH_iGZqaHguccXTI9b6fKJgujtDK2ErElmrZKpc3Ew'.
      System.InvalidOperationException: Cannot provide a value for property 'Localizer' on type 'Havit.Blazor.Components.Web.Bootstrap.HxSidebar'. There is no registered service of type 'Microsoft.Extensions.Localization.IStringLocalizer`1[Havit.Blazor.Components.Web.Bootstrap.HxSpinner]'.
         at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass9_0.<CreatePropertyInjector>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
         at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

Any ideas? I have followed the setup instructions, and I was able to render the test "thumbs up" icon, and the COUNTER page seems to sometimes work, and sometimes throw the error. It's very strange.

**Comment by hakenr** [comment]
This issue is most likely caused by a missing `.AddHxServices()` call in your startup code. 

Please note that for `InteractiveAuto` rendering, the services need to be registered in both the `.Client` project and the main (server) project.

**Comment by rgbinnovation** [comment]
Many thanks, appreciate it! This was a bit vague in the documentation, maybe point it out more? Currently it reads (step 4):

"Add the following line of code to your services registration, typically found in the Program.cs file of your Blazor client project:"

Maybe change to "add in the Program.cs files of both the Server and Client project."? Just a suggestion :-)

**Comment by hakenr** [comment]
The common pattern is to create an `.AddClientServices()` method in the `Client` project and place all shared registrations there. The main (server) project then calls `.AddClientServices()` to make these services available for server-side rendering as well.

Sample code (for our Premium sponsors/subscribers):
* https://github.com/havit/Havit.Blazor.Premium/blob/main/blocks/BlocksApp.Client/DependencyInjection.cs
* https://github.com/havit/Havit.Blazor.Premium/blob/5ecb42636343a875a86e69693d4200aa91c63700/blocks/BlocksApp/Program.cs#L11

...but you're correct; I'll update the initial instructions to clarify this.
