### ISSUE TITLE
[HxCarousel] Demo page often throws JS error: Illegal invocation when leaving the page

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#904]
Display /components/HxCarousel move to /components/HxCheckbox.
```
selector-engine.js:37  Uncaught TypeError: Illegal invocation
    at Object.find (selector-engine.js:37:60)
    at xt._getItems (carousel.js:381:27)
    at xt._getItemIndex (carousel.js:267:17)
    at r (carousel.js:319:20)
    at carousel.js:362:7
    at g (index.js:226:51)
    at HTMLDivElement.a (index.js:247:5)
    at s (index.js:71:11)
    at index.js:253:7
```

**Comment by hakenr** [comment]
This happens because Bootstrap tries to complete the `slid` event even though the carousel no longer exists.  
Unfortunately, there's not much we can do about it - this would need to be resolved on Bootstrap's end.
