### ISSUE TITLE
[doc] PersistentComponentState while prerendering: There is already a persisted object under the same key 'ColorMode'

### ISSUE THREAD

**Issue by hakenr** [havit/Havit.Blazor#948]
```
﻿fail: Microsoft.AspNetCore.Components.Infrastructure.ComponentStatePersistenceManager[1000]
﻿      There was an error executing a callback while pausing the application.
﻿      System.ArgumentException: There is already a persisted object under the same key 'ColorMode'
﻿         at Microsoft.AspNetCore.Components.PersistentComponentState.PersistAsJson[TValue](String key, TValue instance)
﻿         at Havit.Blazor.Documentation.Shared.Components.DocColorMode.DocColorModeSwitcher.PersistMode() in E:\source\002.HFW-Havit.Blazor\Havit.Blazor.Documentation\Shared\Components\DocColorMode\DocColorModeSwitcher.razor.cs:line 40
﻿         at Microsoft.AspNetCore.Components.Infrastructure.ComponentStatePersistenceManager.<PauseAsync>g__ExecuteCallback|11_0(Func`1 callback, ILogger`1 logger)
```

**Comment by hakenr** [comment]
The issue with the `DocColorModeSwitcher` component is that it was originally designed to appear only once on a page. Now that we've added the `NavBar` with a second instance, the two instances:

- Both try to save their state to `PersistentComponentState`.
- Don't synchronize their states with each other (when you switch the mode in one instance, the other doesn't reflect the change and keeps rendering the original icon).

We have to create a scoped service which will handle the state for both instances (or possibly use existing `IDocColorModeResolver`).
