### ISSUE TITLE
[HxCarousel] IllegalInvocation error when element is removed from DOM during sliding transition

### ISSUE THREAD

**Issue by alexax578** [havit/Havit.Blazor#949]
Exception that is thrown from the Bootstrap carousel component code:

selector-engine.js:37 Uncaught TypeError: Illegal invocation
    at Object.find (selector-engine.js:37:60)
    at xt._getItems (carousel.js:381:27)
    at xt._getItemIndex (carousel.js:267:17)
    at r (carousel.js:319:20)
    at carousel.js:362:7
    at g (index.js:226:51)
    at HTMLDivElement.a (index.js:247:5)
    at s (index.js:71:11)
    at index.js:253:7

Based on the discussion that I found here: https://github.com/twbs/bootstrap/issues/38373
and based on the implementation of Bootstrap components for React that were mentioned in the issue: https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Carousel.tsx

I am not sure if this Bootstrap team will be willing to resolve this issue. When I look at the implementation of the Carousel component in react-bootstrap they do not rely on Bootstrap to handle the logic. Instead, they implement it on their own to better handle interactions with React.

**Comment by hakenr** [comment]
Duplicates #904.
